title = input("Enter the book title: ")
author = input("Enter the author: ")
publication = input("Enter the year of publication: ")
genre_name = input("Enter the genre: ")
lib_name = input("Enter the library: ")
memID = input("Enter your memberID: ")
return_date = input("Enter the return date: ")
print("You have successfully reserved the book '%s' by %s."% (title,author))
print("Year of Publication: %d"% (publication))
print("Genre: %s"% (genre_name))
print("Library: %s"% (lib_name))
print("Member ID: %d"% (memID))
print("Return Date: %s"% (return_date))
